class AdvancedCSSGenerator {
  constructor() {
    this.breakpoints = {
      mobile: '480px',
      tablet: '768px',
      desktop: '1024px',
      large: '1200px'
    };
  }

  generateCSS(analysis) {
    console.log('🎨 Generating advanced CSS...');
    
    const { imageInfo, elements, layout, colorPalette } = analysis;
    
    const css = `/* Advanced CSS Generated by AI */
/* Image Analysis: ${imageInfo.width}x${imageInfo.height}px */
/* Layout Type: ${layout.type} */
/* Elements: ${elements.length} */

/* CSS Variables */
:root {
    --primary-color: ${colorPalette.primary};
    --secondary-color: ${colorPalette.secondary};
    --background-color: ${colorPalette.background};
    --text-color: ${this.getContrastColor(colorPalette.background)};
    --accent-color: ${colorPalette.dominant[3] || '#007bff'};
    --border-color: ${this.lightenColor(colorPalette.primary, 0.3)};
    --shadow-color: ${this.darkenColor(colorPalette.background, 0.1)};
    
    /* Layout Variables */
    --header-height: ${layout.headerHeight}px;
    --footer-height: ${layout.footerHeight}px;
    --content-width: ${imageInfo.width}px;
    --content-height: ${imageInfo.height}px;
    
    /* Typography */
    --font-family: 'Tahoma', 'Arial', 'Helvetica', sans-serif;
    --font-size-base: 16px;
    --line-height-base: 1.6;
    
    /* Spacing */
    --spacing-xs: 4px;
    --spacing-sm: 8px;
    --spacing-md: 16px;
    --spacing-lg: 24px;
    --spacing-xl: 32px;
    
    /* Border Radius */
    --border-radius-sm: 4px;
    --border-radius-md: 8px;
    --border-radius-lg: 12px;
    
    /* Shadows */
    --shadow-sm: 0 2px 4px var(--shadow-color);
    --shadow-md: 0 4px 8px var(--shadow-color);
    --shadow-lg: 0 8px 16px var(--shadow-color);
}

/* Reset and Base Styles */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

html {
    font-size: var(--font-size-base);
    line-height: var(--line-height-base);
}

body {
    font-family: var(--font-family);
    background-color: var(--background-color);
    color: var(--text-color);
    direction: rtl;
    overflow-x: auto;
    min-height: 100vh;
}

/* Layout Container */
.image-container {
    position: relative;
    width: var(--content-width);
    height: var(--content-height);
    margin: 0 auto;
    background-color: var(--background-color);
    border: 2px solid var(--border-color);
    border-radius: var(--border-radius-lg);
    box-shadow: var(--shadow-lg);
    overflow: hidden;
}

/* Header Styles */
.page-header {
    position: relative;
    background: linear-gradient(135deg, var(--primary-color), var(--secondary-color));
    color: var(--text-color);
    border-bottom: 1px solid var(--border-color);
    z-index: 10;
}

.header-content {
    position: relative;
    height: 100%;
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: var(--spacing-md);
}

/* Main Content Styles */
.main-content {
    position: relative;
    min-height: calc(100% - var(--header-height) - var(--footer-height));
    background-color: var(--background-color);
}

.content-wrapper {
    position: relative;
    height: 100%;
    padding: var(--spacing-md);
}

/* Layout Types */
.single-column .content-wrapper {
    display: flex;
    flex-direction: column;
    gap: var(--spacing-md);
}

.multi-column .content-wrapper {
    display: grid;
    grid-template-columns: repeat(var(--columns, 2), 1fr);
    gap: var(--spacing-lg);
}

.grid-layout .content-wrapper {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: var(--spacing-md);
}

/* Footer Styles */
.page-footer {
    position: relative;
    background: linear-gradient(135deg, var(--secondary-color), var(--primary-color));
    color: var(--text-color);
    border-top: 1px solid var(--border-color);
    z-index: 10;
}

.footer-content {
    position: relative;
    height: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: var(--spacing-md);
}

/* Element Styles */
.text-element {
    position: absolute;
    display: flex;
    align-items: center;
    justify-content: center;
    background-color: rgba(255, 255, 255, 0.95);
    border: 1px solid var(--border-color);
    border-radius: var(--border-radius-sm);
    padding: var(--spacing-sm);
    font-size: 14px;
    font-weight: 500;
    text-align: center;
    color: var(--text-color);
    box-shadow: var(--shadow-sm);
    transition: all 0.3s ease;
    cursor: pointer;
    backdrop-filter: blur(10px);
}

.text-element:hover {
    transform: translateY(-2px);
    box-shadow: var(--shadow-md);
    background-color: rgba(255, 255, 255, 1);
}

.image-element {
    position: absolute;
    display: flex;
    align-items: center;
    justify-content: center;
    background: linear-gradient(135deg, #f8f9fa, #e9ecef);
    border: 2px solid var(--border-color);
    border-radius: var(--border-radius-md);
    box-shadow: var(--shadow-sm);
    transition: all 0.3s ease;
    cursor: pointer;
    overflow: hidden;
}

.image-element:hover {
    transform: scale(1.02);
    box-shadow: var(--shadow-md);
    border-color: var(--accent-color);
}

.image-placeholder {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    font-size: 12px;
    color: #6c757d;
    text-align: center;
    padding: var(--spacing-sm);
}

/* Element Types */
.element {
    position: absolute;
    display: flex;
    align-items: center;
    justify-content: center;
    border-radius: var(--border-radius-sm);
    transition: all 0.3s ease;
    cursor: pointer;
}

.element:hover {
    transform: scale(1.02);
    box-shadow: var(--shadow-md);
}

/* Original Image Overlay */
.original-image-overlay {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    pointer-events: none;
    z-index: -1;
}

.original-image-overlay img {
    width: 100%;
    height: 100%;
    object-fit: contain;
    opacity: 0.05;
    filter: blur(1px);
}

/* Responsive Design */
@media (max-width: ${this.breakpoints.large}) {
    .image-container {
        width: 100%;
        max-width: 1200px;
        height: auto;
        aspect-ratio: var(--content-width) / var(--content-height);
    }
    
    .multi-column .content-wrapper {
        grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    }
}

@media (max-width: ${this.breakpoints.desktop}) {
    .image-container {
        max-width: 1024px;
    }
    
    .multi-column .content-wrapper {
        grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
    }
    
    .text-element {
        font-size: 12px;
        padding: var(--spacing-xs);
    }
}

@media (max-width: ${this.breakpoints.tablet}) {
    .image-container {
        max-width: 768px;
        border-radius: var(--border-radius-md);
    }
    
    .multi-column .content-wrapper {
        grid-template-columns: 1fr;
    }
    
    .grid-layout .content-wrapper {
        grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
    }
    
    .text-element {
        font-size: 11px;
    }
    
    .image-placeholder {
        font-size: 10px;
    }
}

@media (max-width: ${this.breakpoints.mobile}) {
    .image-container {
        max-width: 480px;
        border-radius: var(--border-radius-sm);
    }
    
    .grid-layout .content-wrapper {
        grid-template-columns: 1fr;
    }
    
    .text-element {
        font-size: 10px;
        padding: 2px;
    }
    
    .image-placeholder {
        font-size: 9px;
    }
    
    .header-content,
    .footer-content {
        padding: var(--spacing-sm);
    }
}

/* Print Styles */
@media print {
    .image-container {
        width: 100%;
        height: auto;
        border: none;
        box-shadow: none;
    }
    
    .text-element,
    .image-element {
        position: static;
        display: block;
        margin: var(--spacing-sm) 0;
        break-inside: avoid;
    }
    
    .original-image-overlay {
        display: none;
    }
}

/* Accessibility */
@media (prefers-reduced-motion: reduce) {
    * {
        animation-duration: 0.01ms !important;
        animation-iteration-count: 1 !important;
        transition-duration: 0.01ms !important;
    }
}

/* High Contrast Mode */
@media (prefers-contrast: high) {
    .text-element {
        border: 2px solid var(--text-color);
        background-color: var(--background-color);
    }
    
    .image-element {
        border: 3px solid var(--text-color);
    }
}

/* Dark Mode Support */
@media (prefers-color-scheme: dark) {
    :root {
        --background-color: #1a1a1a;
        --text-color: #ffffff;
        --border-color: #444444;
        --shadow-color: rgba(0, 0, 0, 0.5);
    }
    
    .text-element {
        background-color: rgba(0, 0, 0, 0.8);
        color: #ffffff;
    }
    
    .image-element {
        background: linear-gradient(135deg, #2d2d2d, #1a1a1a);
    }
}`;

    console.log('✅ Advanced CSS generated');
    return css;
  }

  getContrastColor(hexColor) {
    const r = parseInt(hexColor.slice(1, 3), 16);
    const g = parseInt(hexColor.slice(3, 5), 16);
    const b = parseInt(hexColor.slice(5, 7), 16);
    const luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
    return luminance > 0.5 ? '#000000' : '#ffffff';
  }

  lightenColor(hexColor, factor) {
    const r = Math.min(255, parseInt(hexColor.slice(1, 3), 16) + (255 * factor));
    const g = Math.min(255, parseInt(hexColor.slice(3, 5), 16) + (255 * factor));
    const b = Math.min(255, parseInt(hexColor.slice(5, 7), 16) + (255 * factor));
    return `#${r.toString(16).padStart(2, '0')}${g.toString(16).padStart(2, '0')}${b.toString(16).padStart(2, '0')}`;
  }

  darkenColor(hexColor, factor) {
    const r = Math.max(0, parseInt(hexColor.slice(1, 3), 16) - (255 * factor));
    const g = Math.max(0, parseInt(hexColor.slice(3, 5), 16) - (255 * factor));
    const b = Math.max(0, parseInt(hexColor.slice(5, 7), 16) - (255 * factor));
    return `#${r.toString(16).padStart(2, '0')}${g.toString(16).padStart(2, '0')}${b.toString(16).padStart(2, '0')}`;
  }
}

module.exports = { AdvancedCSSGenerator };